name: Check

"on":
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run lint
        id: lint
        run: |
          npm run lint || echo "lint_result=fail" >> "$GITHUB_LIST_STATUS"
          
      - name: Output lint errors
        if: failure()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Lint Check
          message: |
            **Lint Check Failed** :x:
            ```
            ${{ steps.tests.outputs.stdout }}   
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Add PR comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Lint results:
              \`\`\`bash
                ${{ steps.tests.outputs.stdout }}  
              \`\`\`
              `
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
