name: Lint Check
"on": 
  pull_request:
    types: [opened, edited]
jobs:
  lint-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              npm ci
              npm run build
              npm run test:unit
              npm run lint
